# 1. Make sure docker gzipped authentication is available at host
# 2. POST app.json.j2 template to Marathon API

---
  - set_fact:
      request_body: {
        "id": "akka-docker",
        "cpus": 0.3,
        "mem": 256.0,
        "instances": 1,
        "uris": ["file:///etc/docker.tar.gz"],
        "container": {
            "type": "DOCKER",
            "docker": {
              "image": "benniekrijger/akkadocker:1.0",
              "network": "BRIDGE",
              "portMappings": [
                  { "containerPort": 8080, "hostPort": 0, "protocol": "tcp" }
              ]
            }
        },
        "healthChecks": [
          {
            "path": "/api",
            "portIndex": 0,
            "protocol": "HTTP",
            "gracePeriodSeconds": 300,
            "intervalSeconds": 60,
            "timeoutSeconds": 20
          }
        ]
      }
    tags:
      - deploy

  - name: FrontendApp Deploy | Kick off marathon app
    uri: url=http://master:8080/v2/apps/akkadocker-{{version}}
       method=PUT
       body='{{ request_body | to_json }}'
       HEADER_Content-Type="application/json"
       status_code=200,201,204
    tags:
      - deploy